### ISSUE TITLE
未找到"limit/attr_correlation.txt"文件

### ISSUE THREAD

**Issue by citrontyan** [thunlp/KR-EAR#2]
代码中需要读取"limit/attr_correlation.txt"文件（TransE版本main.cpp第785行，TransR版本main.cpp第920行），这个文件既不在代码文件中，也不在data包中。请问：
1.      该文件是否必须？我在Ubuntu16.04中使用g++ 5.3.1编译源码运行后会在对该文件的fscanf函数中产生Runtime Error，如果注释掉相关代码会对实验结果产生怎样的影响？
2.      该文件的内容和作用是什么？
3.      如果该文件必须，我该如何获取该文件从而恢复实验？

**Comment by Mrlyk423** [comment]
1、2：该文件为论文中Attribute Correlations和Correlation between Relations & Attributes两个优化的必要文件
3： 已上传该文件。

**Comment by gsp2014** [comment]
您好，“limit/attr_correlation.txt”文件是属性的Correlations，每行格式为：属性1 \t 值1 \t 属性2 \t 值2 \t Correlations，这个Correlations是怎么计算得到的呢？
