### ISSUE TITLE
关于“limit/attr_correlation.txt”文件计算方法

### ISSUE THREAD

**Issue by gsp2014** [thunlp/KR-EAR#3]
您好，“limit/attr_correlation.txt”文件是属性的Correlations，每行格式为：属性1 \t 值1 \t 属性2 \t 值2 \t Correlations，这个Correlations是怎么计算得到的呢？

**Comment by Mrlyk423** [comment]
你好，在train文件中直接统计所有entity下attribute的共现即可。

**Comment by gsp2014** [comment]
也就是说属性1、值1、属性2和值2在train-attr.txt文件中一起出现的次数除以属性1和属性2（值任意）一起出现的次数，对吗？对于train-rel.txt文件中的关系计算这样的Correlations吗？

**Comment by Mrlyk423** [comment]
对的。
