### ISSUE TITLE
关于"limit/left.txt"和"limit/right.txt"文件

### ISSUE THREAD

**Issue by gsp2014** [thunlp/KR-EAR#4]
您好，test的时候缺少"limit/left.txt"和"limit/right.txt"这两个文件，每行为关系、属性、值，这两个文件怎么得到？是关系r、属性a、值v一起出现的次数除以关系r和属性a一起出现的次数？"limit/left.txt"和"limit/right.txt"这两个文件内容有什么区别呢？

**Comment by Mrlyk423** [comment]
见新上传附件。left.txt为一个关系rel下head entity的attribute对应的某个value的估计概率，在train下统计得到，right.txt同理。

**Comment by gsp2014** [comment]
能否给出计算的代码，自己计算的limit下的三个文件attr_correlation.txt、left.txt和right.txt和给出的还是不一样。

**Comment by Mrlyk423** [comment]
见https://pan.baidu.com/s/1kUXJ4Z9，这部分代码没整理，比较乱。
