### ISSUE TITLE
关于程序运行

### ISSUE THREAD

**Issue by gsp2014** [thunlp/KR-EAR#5]
您好，关于程序运行有两个问题请教：（1）相同的配置多次运行结果不一致，感觉很奇怪，怎么解释呢？（2）按文章的配置，没有重现文章的结果，差一些。

**Comment by Mrlyk423** [comment]
（1）我运行的时候基本上都是一致的，会有小的浮动，不知道你的运行结果不一致指的是？
（2）差一些指的是？

**Comment by gsp2014** [comment]
有百分之几的浮动，这个正常吗？另外KR-EAR(TransR)代码中的迭代轮数为300，将其改为了文章说的迭代轮数1000。

**Comment by Mrlyk423** [comment]
不太正常吧，我当时运行时不同次运行结果应该差距不会超过1~2%。
